package nono

import "fmt"

// String methods for exported enum types make log output and test failure
// messages human-readable without requiring callers to import fmt.
//
// These are hand-written (not generated by golang.org/x/tools/cmd/stringer)
// because the underlying values are sourced from C enum constants via CGo;
// the stringer tool cannot read CGo-bound constants and would produce a broken
// file. Do NOT add a //go:generate stringer directive for these types.

// String returns a human-readable representation of the access mode.
func (m AccessMode) String() string {
	switch m {
	case AccessRead:
		return "read"
	case AccessWrite:
		return "write"
	case AccessReadWrite:
		return "read-write"
	default:
		return fmt.Sprintf("AccessMode(%d)", uint32(m))
	}
}

// String returns a human-readable representation of the network mode.
func (m NetworkMode) String() string {
	switch m {
	case NetworkBlocked:
		return "blocked"
	case NetworkAllowAll:
		return "allow-all"
	case NetworkProxyOnly:
		return "proxy-only"
	default:
		return fmt.Sprintf("NetworkMode(%d)", uint32(m))
	}
}

// String returns a human-readable representation of the capability source tag.
func (s CapabilitySourceTag) String() string {
	switch s {
	case SourceUser:
		return "user"
	case SourceGroup:
		return "group"
	case SourceSystem:
		return "system"
	case SourceProfile:
		return "profile"
	default:
		return fmt.Sprintf("CapabilitySourceTag(%d)", int(s))
	}
}

// String returns a human-readable representation of the query status.
func (s QueryStatus) String() string {
	switch s {
	case QueryAllowed:
		return "allowed"
	case QueryDenied:
		return "denied"
	default:
		return fmt.Sprintf("QueryStatus(%d)", int(s))
	}
}

// String returns a human-readable representation of the query reason.
func (r QueryReason) String() string {
	switch r {
	case ReasonGrantedPath:
		return "granted-path"
	case ReasonNetworkAllowed:
		return "network-allowed"
	case ReasonPathNotGranted:
		return "path-not-granted"
	case ReasonInsufficientAccess:
		return "insufficient-access"
	case ReasonNetworkBlocked:
		return "network-blocked"
	default:
		return fmt.Sprintf("QueryReason(%d)", int(r))
	}
}
